{
 "title": "Panel aplikacji listy zadań",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Liczba utworzonych zadań",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "todo_tasks_created_total", "legendFormat": "Liczba zadań" }
   ]
  },
  {
   "title": "Całkowita liczba obsłużonych żądań HTTP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_received_total",
     "legendFormat": "Metoda = {{method}}, Kod = {{code}}"
    }
   ]
  },
  {
   "title": "Liczba aktualnie przetwarzanych żądań HTTP",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_in_progress",
     "legendFormat": "Liczba przetwarzanych żądań HTTP"
    }
   ]
  }
 ]
}